version: '3'

services:
  portfolio:
    image: jasonruesch/portfolio:latest
    container_name: portfolio
    build:
      context: .
      dockerfile: ./apps/portfolio/Dockerfile.prod
    ports:
      - '8081:80'

  admin:
    image: jasonruesch/admin:latest
    container_name: admin
    build:
      context: .
      dockerfile: ./apps/admin/Dockerfile.prod
    ports:
      - '8082:80'
