name: Tag CI

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

# This file builds docker images whenever a new tag is pushed
on:
  push:
    tags:
      - '*'

jobs:
  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    env:
      INPUT_PUSH: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: 'lts/*'
      - run: npm ci
      - run: npx nx run-many --target=build --all
      - run: npx nx run-many --target=container --all --parallel=2 --configuration=ci
        env:
          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
