# This workflow will do a clean installation of node dependencies, cache/restore them and run tests
# It will also automerge dependabot PRs

name: CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      pr-number:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Use Node.js 16
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      # - run: npm run build --if-present
      - run: npm test
  automerge:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' }}
        with:
          github-token: ${{secrets.github_token}}
          merge-method: 'rebase'
