name: CI

on:
  push:
    branches:
      - main
  pull_request:

# Needed for nx-set-shas within nx-cloud-main.yml, when run on the main branch
permissions:
  actions: read
  contents: read

jobs:
  # main:
  #   name: Nx Cloud - Main Job
  #   uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.13.1
  #   with:
  #     main-branch-name: main
  #     number-of-agents: 3
  #     init-commands: |
  #       npx nx-cloud start-ci-run --stop-agents-after="build" --agent-count=3
  #     parallel-commands: |
  #       npx nx-cloud record -- npx nx format:check
  #     parallel-commands-on-agents: |
  #       npx nx affected --target=lint --parallel=3
  #       npx nx affected --target=test --parallel=3 --ci --code-coverage
  #       npx nx affected --target=build --parallel=3

  # agents:
  #   name: Nx Cloud - Agents
  #   uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.13.1
  #   with:
  #     number-of-agents: 3
  main:
    name: Main Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.x
          cache: npm

      - name: Install
        run: npm ci

      - name: Lint
        run: npx nx affected --target=lint --parallel=3
      - name: Test
        run: npx nx affected --target=test --parallel=3 --ci --code-coverage
      - name: Build
        run: npx nx affected --target=build --parallel=3
