name: Continuous Integration
on:
  pull_request:
    paths:
      - '**.ts'
      - '**.scss'
      - '**.html'
      - '**.json'

env:
  NX_BRANCH: ${{ github.head_ref }}
  NX_RUN_GROUP: ${{ github.run_id }}

jobs:
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.head_ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm ci
      - name: Build
        run: npx nx affected --target=build --parallel --max-parallel=3
